### ISSUE TITLE
确实需要做对齐，目前的模型还很难讲用户体验

### ISSUE THREAD

**Issue by cookyecat** [xverse-ai/XVERSE-13B#11]
目前的 Pretrained 版应该是可以完成 NLP 基础任务。但是对话方面还需要做对齐，测试了几个知识检索方面的问题，输出不太对：
![微信图片_20230808194831](https://github.com/xverse-ai/XVERSE-13B/assets/4266166/43bfaff1-7ed9-44c5-9b2d-bd7cbe8bcfaf)
![微信图片_20230808195026](https://github.com/xverse-ai/XVERSE-13B/assets/4266166/c427c3f8-924b-42a9-8f11-7f5d72712dff)

**Comment by underspirit** [comment]
近期会发布Chat版模型, 请持续关注.

**Comment by underspirit** [comment]
Chat版模型已发布, 欢迎下载使用
