### ISSUE TITLE
generate 的 stop words 是什么？

### ISSUE THREAD

**Issue by luefei** [xverse-ai/XVERSE-13B#12]
generate 的 stop words 是什么？

**Comment by ouyangliqi** [comment]
请参考README中的Transformers 加载方式：
https://github.com/xverse-ai/XVERSE-13B#transformers-%E5%8A%A0%E8%BD%BD%E6%96%B9%E5%BC%8F

**Comment by underspirit** [comment]
```
tokenizer.eos_token
```
即'<|endoftext|>'
