### ISSUE TITLE
请问如何通过CPU运行该模型

### ISSUE THREAD

**Issue by jiaowobaba02** [xverse-ai/XVERSE-13B#18]
我的电脑的显存很小，才2GB，但是我挺想运行该模型的，之前在Baichuan.cpp项目的帮助下，我通过CPU运行了百川模型，我想，该模型应该也会有类似的解决方案，毕竟这么好的模型如果能火起来，对此功能需求的用户应该不少

**Comment by underspirit** [comment]
可以尝试使用llama.cpp, 已支持XVERSE模型
