### ISSUE TITLE
继续预训练的问题

### ISSUE THREAD

**Issue by dtxwhzw** [xverse-ai/XVERSE-13B#26]
<img width="543" alt="image" src="https://github.com/xverse-ai/XVERSE-13B/assets/38512349/49a605d1-2604-4f9c-a916-f86ad54745a3">

请问一下这里的“ 20% 的预训练数据”，指的是XVERSE-13B-2 的预训练数据里面的20%。还是有一个新的数据集，数据量是原始预训练数据量级的20%呢？

**Comment by miange91** [comment]
> <img alt="image" width="543" src="https://private-user-images.githubusercontent.com/38512349/297698073-49a605d1-2604-4f9c-a916-f86ad54745a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MDc5ODgsIm5iZiI6MTcwNTkwNzY4OCwicGF0aCI6Ii8zODUxMjM0OS8yOTc2OTgwNzMtNDlhNjA1ZDEtMjYwNC00ZjljLWE5MTYtZjg2YWQ1NDc0NWEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA3MTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YzA2YmEzMDZhMDJjMGMwNTFlM2Q2NTA1YjA1ZjE2NWJjNzExYjIwOTllMWRlZWE4MWZjOGU3YTQ4NjcyYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lZx0N8WqOwyydlVxigCF2cnPkwo0wH5CAKSh5dJ2pxE">
> 请问一下这里的“ 20% 的预训练数据”，指的是XVERSE-13B-2 的预训练数据里面的20%。还是有一个新的数据集，数据量是原始预训练数据量级的20%呢？

是XVERSE-13B-2 的预训练数据里面的20%。
