### ISSUE TITLE
XVERSE-13B-256K demo error

### ISSUE THREAD

**Issue by robin-programmer** [xverse-ai/XVERSE-13B#27]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat
    outputs = self.generate(
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward
    outputs = self.model(
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward
    layer_outputs = decoder_layer(
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward
    assert not use_cache, "use_cache is not supported"
AssertionError: use_cache is not supported

**Comment by Quant2017** [comment]
the same is

**Comment by bys0318** [comment]
Model generation becomes extremely slow when setting `use_cache=False`

**Comment by miange91** [comment]
> Traceback (most recent call last): File "", line 1, in File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat outputs = self.generate( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample outputs = self( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward outputs = self.model( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward layer_outputs = decoder_layer( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward assert not use_cache, "use_cache is not supported" AssertionError: use_cache is not supported

please install requirements.txt

**Comment by fangd123** [comment]
> > Traceback (most recent call last): File "", line 1, in File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat outputs = self.generate( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample outputs = self( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward outputs = self.model( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward layer_outputs = decoder_layer( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward assert not use_cache, "use_cache is not supported" AssertionError: use_cache is not supported
> 
> please install requirements.txt

This error is still there

**Comment by miange91** [comment]
> > > Traceback (most recent call last): File "", line 1, in File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat outputs = self.generate( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample outputs = self( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward outputs = self.model( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward layer_outputs = decoder_layer( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward assert not use_cache, "use_cache is not supported" AssertionError: use_cache is not supported
> > 
> > 
> > please install requirements.txt
> 
> This error is still there

Add "use_cache=False" in modeling_xverse.py, in line 247

**Comment by miange91** [comment]
> > > Traceback (most recent call last): File "", line 1, in File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat outputs = self.generate( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample outputs = self( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward outputs = self.model( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward layer_outputs = decoder_layer( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward assert not use_cache, "use_cache is not supported" AssertionError: use_cache is not supported
> > 
> > 
> > please install requirements.txt
> 
> This error is still there

Install the requirements.txt(https://huggingface.co/xverse/XVERSE-13B-256K/blob/main/requirements.txt)
transformers==4.31.0

**Comment by robin-programmer** [comment]
> > > > Traceback (most recent call last): File "", line 1, in File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat outputs = self.generate( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample outputs = self( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward outputs = self.model( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward layer_outputs = decoder_layer( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward assert not use_cache, "use_cache is not supported" AssertionError: use_cache is not supported
> > > 
> > > 
> > > please install requirements.txt
> > 
> > 
> > This error is still there
> 
> Install the requirements.txt(https://huggingface.co/xverse/XVERSE-13B-256K/blob/main/requirements.txt) transformers==4.31.0

confirmed the transformers version, still error

**Comment by fangd123** [comment]
> > > > Traceback (most recent call last): File "", line 1, in File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 840, in chat outputs = self.generate( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate return self.sample( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample outputs = self( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward outputs = self.model( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 603, in forward layer_outputs = decoder_layer( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 311, in forward hidden_states, self_attn_weights, present_key_value = self.self_attn( File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/data/miniconda3/envs/xverse/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 249, in forward assert not use_cache, "use_cache is not supported" AssertionError: use_cache is not supported
> > > 
> > > 
> > > please install requirements.txt
> > 
> > 
> > This error is still there
> 
> Add "use_cache=False" in modeling_xverse.py, in line 247

It report error

```
Exception in thread Thread-7 (generate):
Traceback (most recent call last):
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/transformers/generation/utils.py", line 1588, in generate
    return self.sample(
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/transformers/generation/utils.py", line 2642, in sample
    outputs = self(
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/timenet/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 715, in forward
    outputs = self.model(
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/timenet/miniconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/timenet/.cache/huggingface/modules/transformers_modules/XVERSE-13B-256K/modeling_xverse.py", line 542, in forward
    past_key_values_length = past_key_values[0][0].shape[2]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by heshaojia** [comment]
in the demo code,  add:

model.generation_config.use_cache = False 

And then I can run OK

**Comment by fangd123** [comment]
> in the demo code, add:
> 
> model.generation_config.use_cache = False
> 
> And then I can run OK

It works, thank you !

**Comment by Uchihayht** [comment]
> in the demo code, add:
> 
> model.generation_config.use_cache = False
> 
> And then I can run OK

增加了这一行，但是报错：
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 34, 40, 128) (torch.bfloat16)
     key         : shape=(1, 34, 40, 128) (torch.bfloat16)
     value       : shape=(1, 34, 40, 128) (torch.bfloat16)
     attn_bias   : <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
     p           : 0.1
`decoderF` is not supported because:
    device=cpu (supported: {'cuda'})
    attn_bias type is <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
    dropout > 0.0
    bf16 is only supported on A100+ GPUs
`flshattF@v2.3.2` is not supported because:
    device=cpu (supported: {'cuda'})
    bf16 is only supported on A100+ GPUs
`tritonflashattF` is not supported because:
    device=cpu (supported: {'cuda'})
    dropout > 0.0
    bf16 is only supported on A100+ GPUs
    operator wasn't built - see `python -m xformers.info` for more info
    triton is not available
    Only work on pre-MLIR triton for now
`cutlassF` is not supported because:
    device=cpu (supported: {'cuda'})
    bf16 is only supported on A100+ GPUs
`smallkF` is not supported because:
    max(query.shape[-1] != value.shape[-1]) > 32
    device=cpu (supported: {'cuda'})
    dtype=torch.bfloat16 (supported: {torch.float32})
    attn_bias type is <class 'xformers.ops.fmha.attn_bias.LowerTriangularMask'>
    bf16 is only supported on A100+ GPUs
    unsupported embed per head: 128

**Comment by underspirit** [comment]
可以参考https://github.com/xverse-ai/XVERSE-13B/issues/29#issuecomment-2060284214
