### ISSUE TITLE
就发布一个模型，啥其他工具也没有？

### ISSUE THREAD

**Issue by thewintersun** [xverse-ai/XVERSE-13B#3]
预训练，微调工具都没有？

**Comment by underspirit** [comment]
后续会逐步开放经过SFT的Chat版模型以及相关工具

**Comment by hiyouga** [comment]
可以试试 https://github.com/hiyouga/LLaMA-Efficient-Tuning

**Comment by dongxiaolong** [comment]
> 后续会逐步开放经过SFT的Chat版模型以及相关工具
"What we need most is the dataset. Please release the dataset.

**Comment by underspirit** [comment]
Chat版模型已发布, 欢迎下载使用
