### ISSUE TITLE
Xverse Chat版本模型的template是什么啊

### ISSUE THREAD

**Issue by Tendo33** [xverse-ai/XVERSE-13B#30]
如果想要在xverse_13b_256k模型的基础上做微调的话，使用官方训练的对话template是不是更好呢

**Comment by underspirit** [comment]
https://huggingface.co/xverse/XVERSE-13B-256K/blob/main/modeling_xverse.py#L755
template可以在modeling_xverse.py的`_build_chat_input`函数中看到，微调对齐template会更好.
