### ISSUE TITLE
推理很慢是什么原因

### ISSUE THREAD

**Issue by LLLyyy-777** [xverse-ai/XVERSE-13B#4]
差不多十分钟

**Comment by underspirit** [comment]
请确认是否使用了GPU, 十分钟可能是没用GPU, 而是用的CPU在推理.

**Comment by LLLyyy-777** [comment]
估计是显存不够用device_map放了一部分到cpu了，想问一下模型加载最低显存是多少，谢谢！

**Comment by lfxx** [comment]
> 估计是显存不够用device_map放了一部分到cpu了，想问一下模型加载最低显存是多少，谢谢！

同问，目前放在3090ti上跑不起来，fp16上估计和百川一样要32G吧。如果能推出官方的int8模型降低部署门槛就好了

**Comment by LLLyyy-777** [comment]
> 

试了一下load_in_8bit=True，大概20G

**Comment by LLLyyy-777** [comment]
> > 估计是显存不够用device_map放了一部分到cpu了，想问一下模型加载最低显存是多少，谢谢！
> 
> 同问，目前放在3090ti上跑不起来，fp16上估计和百川一样要32G吧。如果能推出官方的int8模型降低部署门槛就好了

试了一下load_in_8bit=True，大概16G

**Comment by lfxx** [comment]
> > > 估计是显存不够用device_map放了一部分到cpu了，想问一下模型加载最低显存是多少，谢谢！
> > 
> > 
> > 同问，目前放在3090ti上跑不起来，fp16上估计和百川一样要32G吧。如果能推出官方的int8模型降低部署门槛就好了
> 
> 试了一下load_in_8bit=True，大概20G

请问从哪里添加这个参数呢，方便给出一个demo吗

**Comment by LLLyyy-777** [comment]
> > > > 估计是显存不够用device_map放了一部分到cpu了，想问一下模型加载最低显存是多少，谢谢！
> > > 
> > > 
> > > 同问，目前放在3090ti上跑不起来，fp16上估计和百川一样要32G吧。如果能推出官方的int8模型降低部署门槛就好了
> > 
> > 
> > 试了一下load_in_8bit=True，大概16G
> 
> 请问从哪里添加这个参数呢，方便给出一个demo吗

model = AutoModelForCausalLM.from_pretrained("xverse/XVERSE-13B", load_in_8bit=True, trust_remote_code=True, device_map="auto")
