### ISSUE TITLE
只放Base模型难以评估模型真实效果，等chat版本

### ISSUE THREAD

**Issue by xufengnian** [xverse-ai/XVERSE-13B#8]
![image](https://github.com/xverse-ai/XVERSE-13B/assets/15324125/8f26a4e6-40ce-48b2-affd-dda7f71bc6ff)
![image](https://github.com/xverse-ai/XVERSE-13B/assets/15324125/6ade6136-9b7e-4e26-849e-57c08b88810e)
![image](https://github.com/xverse-ai/XVERSE-13B/assets/15324125/c8186503-800c-4dbc-bb9f-d86b028264c3)
模型从https://huggingface.co/xverse/XVERSE-13B

下载的，Base模型这样放出来也比较难评估效果，好歹放一个sft过的chat版本吧，老哥们

**Comment by xufengnian** [comment]
好歹放一个sft过的chat版本吧，老哥们

**Comment by nobodybut** [comment]
我这里加载聊天是对的呀，虽然吃光了我的CPU和内存……如图
![微信截图_20230808141943](https://github.com/xverse-ai/XVERSE-13B/assets/34851831/a9a8aab5-1dea-4926-845e-a414235b6de3)
![微信截图_20230808141931](https://github.com/xverse-ai/XVERSE-13B/assets/34851831/f1d6e8a4-306f-4769-82ea-9d0bbaf6e3e6)
![微信图片_20230808141402](https://github.com/xverse-ai/XVERSE-13B/assets/34851831/b849a1bb-d162-4efe-b3de-d9d03dbb453b)

**Comment by xufengnian** [comment]
> 我这里加载聊天是对的呀，虽然吃光了我的CPU和内存……如图 ![微信截图_20230808141943](https://user-images.githubusercontent.com/34851831/259002525-a9a8aab5-1dea-4926-845e-a414235b6de3.png) ![微信截图_20230808141931](https://user-images.githubusercontent.com/34851831/259002538-f1d6e8a4-306f-4769-82ea-9d0bbaf6e3e6.png) ![微信图片_20230808141402](https://user-images.githubusercontent.com/34851831/259002552-b849a1bb-d162-4efe-b3de-d9d03dbb453b.png)

你这个是直接用了text-generation-webui的chat模式，回答都是英文反而暴露了当前模型不具备问答能力，现有问答能力是原始模型提供（推测llama2-13B）

**Comment by underspirit** [comment]
Chat版模型已发布, 欢迎下载使用
