### ISSUE TITLE
能不能拆成小文件啊，加载内存炸了……

### ISSUE THREAD

**Issue by nobodybut** [xverse-ai/XVERSE-13B#9]
llama2-13b都加载得好好的，XVERSE-13B加载太消耗显存了，切到内存也炸……
参考QWEN-7B的经验，拆成小文件会好很多

**Comment by nobodybut** [comment]
最后氪金加内存解决了，占用内存有点离谱，考虑优化一下不？
![微信图片_20230808141402](https://github.com/xverse-ai/XVERSE-13B/assets/34851831/11092eb3-d132-4f43-89ea-b72580cd9f54)

**Comment by underspirit** [comment]
Chat版模型已发布, 且拆分为了多个小文件, 欢迎下载使用
